# Sidebar navigation

- label: '首页'
  link: '/'
- label: 微信非官方文档
  items:
    - label: '25 位银行账户'
      link: '/pages/wechat/25-yinhang-zhanghao'
- label: 企业级 Web 应用开发
  items:
    - label: 'Page'
      link: '/pro-web/ch01/page'
- label: Awesome
  items:
    - label: '职业'
      link: '/pages/awesome/career'
    - label: '研报'
      link: '/pages/research-report/'
- label: Lorem
  items:
    - label: '微博'
      link: '/pages/lorem/weibo'
- label: More
  items:
    - label: 'Github'
      link: https://github.com/lisitede/lisitede.github.io
